package com.lssm.mapper;

import com.lssm.model.LemonGroup;
import com.lssm.model.LemonGroupExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LemonGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lemon_group
     *
     * @mbggenerated Wed Jun 08 09:49:09 GMT+08:00 2016
     */
    int countByExample(LemonGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lemon_group
     *
     * @mbggenerated Wed Jun 08 09:49:09 GMT+08:00 2016
     */
    int deleteByExample(LemonGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lemon_group
     *
     * @mbggenerated Wed Jun 08 09:49:09 GMT+08:00 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lemon_group
     *
     * @mbggenerated Wed Jun 08 09:49:09 GMT+08:00 2016
     */
    int insert(LemonGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lemon_group
     *
     * @mbggenerated Wed Jun 08 09:49:09 GMT+08:00 2016
     */
    int insertSelective(LemonGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lemon_group
     *
     * @mbggenerated Wed Jun 08 09:49:09 GMT+08:00 2016
     */
    List<LemonGroup> selectByExample(LemonGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lemon_group
     *
     * @mbggenerated Wed Jun 08 09:49:09 GMT+08:00 2016
     */
    LemonGroup selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lemon_group
     *
     * @mbggenerated Wed Jun 08 09:49:09 GMT+08:00 2016
     */
    int updateByExampleSelective(@Param("record") LemonGroup record, @Param("example") LemonGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lemon_group
     *
     * @mbggenerated Wed Jun 08 09:49:09 GMT+08:00 2016
     */
    int updateByExample(@Param("record") LemonGroup record, @Param("example") LemonGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lemon_group
     *
     * @mbggenerated Wed Jun 08 09:49:09 GMT+08:00 2016
     */
    int updateByPrimaryKeySelective(LemonGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lemon_group
     *
     * @mbggenerated Wed Jun 08 09:49:09 GMT+08:00 2016
     */
    int updateByPrimaryKey(LemonGroup record);
}