package com.lssm.mapper;

import com.lssm.model.LemonSeatInfo;
import com.lssm.model.LemonSeatInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LemonSeatInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lemon_seat_info
     *
     * @mbggenerated Wed Jun 08 09:49:09 GMT+08:00 2016
     */
    int countByExample(LemonSeatInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lemon_seat_info
     *
     * @mbggenerated Wed Jun 08 09:49:09 GMT+08:00 2016
     */
    int deleteByExample(LemonSeatInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lemon_seat_info
     *
     * @mbggenerated Wed Jun 08 09:49:09 GMT+08:00 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lemon_seat_info
     *
     * @mbggenerated Wed Jun 08 09:49:09 GMT+08:00 2016
     */
    int insert(LemonSeatInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lemon_seat_info
     *
     * @mbggenerated Wed Jun 08 09:49:09 GMT+08:00 2016
     */
    int insertSelective(LemonSeatInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lemon_seat_info
     *
     * @mbggenerated Wed Jun 08 09:49:09 GMT+08:00 2016
     */
    List<LemonSeatInfo> selectByExample(LemonSeatInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lemon_seat_info
     *
     * @mbggenerated Wed Jun 08 09:49:09 GMT+08:00 2016
     */
    LemonSeatInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lemon_seat_info
     *
     * @mbggenerated Wed Jun 08 09:49:09 GMT+08:00 2016
     */
    int updateByExampleSelective(@Param("record") LemonSeatInfo record, @Param("example") LemonSeatInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lemon_seat_info
     *
     * @mbggenerated Wed Jun 08 09:49:09 GMT+08:00 2016
     */
    int updateByExample(@Param("record") LemonSeatInfo record, @Param("example") LemonSeatInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lemon_seat_info
     *
     * @mbggenerated Wed Jun 08 09:49:09 GMT+08:00 2016
     */
    int updateByPrimaryKeySelective(LemonSeatInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lemon_seat_info
     *
     * @mbggenerated Wed Jun 08 09:49:09 GMT+08:00 2016
     */
    int updateByPrimaryKey(LemonSeatInfo record);
}