package com.lssm.mapper;

import com.lssm.model.LemonUser;
import com.lssm.model.LemonUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LemonUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lemon_user
     *
     * @mbggenerated Wed Jun 08 09:49:09 GMT+08:00 2016
     */
    int countByExample(LemonUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lemon_user
     *
     * @mbggenerated Wed Jun 08 09:49:09 GMT+08:00 2016
     */
    int deleteByExample(LemonUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lemon_user
     *
     * @mbggenerated Wed Jun 08 09:49:09 GMT+08:00 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lemon_user
     *
     * @mbggenerated Wed Jun 08 09:49:09 GMT+08:00 2016
     */
    int insert(LemonUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lemon_user
     *
     * @mbggenerated Wed Jun 08 09:49:09 GMT+08:00 2016
     */
    int insertSelective(LemonUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lemon_user
     *
     * @mbggenerated Wed Jun 08 09:49:09 GMT+08:00 2016
     */
    List<LemonUser> selectByExample(LemonUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lemon_user
     *
     * @mbggenerated Wed Jun 08 09:49:09 GMT+08:00 2016
     */
    LemonUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lemon_user
     *
     * @mbggenerated Wed Jun 08 09:49:09 GMT+08:00 2016
     */
    int updateByExampleSelective(@Param("record") LemonUser record, @Param("example") LemonUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lemon_user
     *
     * @mbggenerated Wed Jun 08 09:49:09 GMT+08:00 2016
     */
    int updateByExample(@Param("record") LemonUser record, @Param("example") LemonUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lemon_user
     *
     * @mbggenerated Wed Jun 08 09:49:09 GMT+08:00 2016
     */
    int updateByPrimaryKeySelective(LemonUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lemon_user
     *
     * @mbggenerated Wed Jun 08 09:49:09 GMT+08:00 2016
     */
    int updateByPrimaryKey(LemonUser record);
}