package com.lssm.model;

public class LemonGroupUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lemon_group_user.id
     *
     * @mbggenerated Wed Jun 08 09:49:09 GMT+08:00 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lemon_group_user.group_id
     *
     * @mbggenerated Wed Jun 08 09:49:09 GMT+08:00 2016
     */
    private Integer groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lemon_group_user.user_id
     *
     * @mbggenerated Wed Jun 08 09:49:09 GMT+08:00 2016
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lemon_group_user.leve
     *
     * @mbggenerated Wed Jun 08 09:49:09 GMT+08:00 2016
     */
    private Boolean leve;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lemon_group_user.id
     *
     * @return the value of lemon_group_user.id
     *
     * @mbggenerated Wed Jun 08 09:49:09 GMT+08:00 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lemon_group_user.id
     *
     * @param id the value for lemon_group_user.id
     *
     * @mbggenerated Wed Jun 08 09:49:09 GMT+08:00 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lemon_group_user.group_id
     *
     * @return the value of lemon_group_user.group_id
     *
     * @mbggenerated Wed Jun 08 09:49:09 GMT+08:00 2016
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lemon_group_user.group_id
     *
     * @param groupId the value for lemon_group_user.group_id
     *
     * @mbggenerated Wed Jun 08 09:49:09 GMT+08:00 2016
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lemon_group_user.user_id
     *
     * @return the value of lemon_group_user.user_id
     *
     * @mbggenerated Wed Jun 08 09:49:09 GMT+08:00 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lemon_group_user.user_id
     *
     * @param userId the value for lemon_group_user.user_id
     *
     * @mbggenerated Wed Jun 08 09:49:09 GMT+08:00 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lemon_group_user.leve
     *
     * @return the value of lemon_group_user.leve
     *
     * @mbggenerated Wed Jun 08 09:49:09 GMT+08:00 2016
     */
    public Boolean getLeve() {
        return leve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lemon_group_user.leve
     *
     * @param leve the value for lemon_group_user.leve
     *
     * @mbggenerated Wed Jun 08 09:49:09 GMT+08:00 2016
     */
    public void setLeve(Boolean leve) {
        this.leve = leve;
    }
}