package com.lssm.model;

public class LemonSeatInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lemon_seat_info.id
     *
     * @mbggenerated Wed Jun 08 09:49:09 GMT+08:00 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lemon_seat_info.seat_num
     *
     * @mbggenerated Wed Jun 08 09:49:09 GMT+08:00 2016
     */
    private Integer seatNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lemon_seat_info.status
     *
     * @mbggenerated Wed Jun 08 09:49:09 GMT+08:00 2016
     */
    private Boolean status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lemon_seat_info.id
     *
     * @return the value of lemon_seat_info.id
     *
     * @mbggenerated Wed Jun 08 09:49:09 GMT+08:00 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lemon_seat_info.id
     *
     * @param id the value for lemon_seat_info.id
     *
     * @mbggenerated Wed Jun 08 09:49:09 GMT+08:00 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lemon_seat_info.seat_num
     *
     * @return the value of lemon_seat_info.seat_num
     *
     * @mbggenerated Wed Jun 08 09:49:09 GMT+08:00 2016
     */
    public Integer getSeatNum() {
        return seatNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lemon_seat_info.seat_num
     *
     * @param seatNum the value for lemon_seat_info.seat_num
     *
     * @mbggenerated Wed Jun 08 09:49:09 GMT+08:00 2016
     */
    public void setSeatNum(Integer seatNum) {
        this.seatNum = seatNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lemon_seat_info.status
     *
     * @return the value of lemon_seat_info.status
     *
     * @mbggenerated Wed Jun 08 09:49:09 GMT+08:00 2016
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lemon_seat_info.status
     *
     * @param status the value for lemon_seat_info.status
     *
     * @mbggenerated Wed Jun 08 09:49:09 GMT+08:00 2016
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }
}