package com.lssm.model;

public class LemonGroup {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lemon_group.id
     *
     * @mbggenerated Wed Jun 08 09:49:09 GMT+08:00 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lemon_group.name
     *
     * @mbggenerated Wed Jun 08 09:49:09 GMT+08:00 2016
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lemon_group.id
     *
     * @return the value of lemon_group.id
     *
     * @mbggenerated Wed Jun 08 09:49:09 GMT+08:00 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lemon_group.id
     *
     * @param id the value for lemon_group.id
     *
     * @mbggenerated Wed Jun 08 09:49:09 GMT+08:00 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lemon_group.name
     *
     * @return the value of lemon_group.name
     *
     * @mbggenerated Wed Jun 08 09:49:09 GMT+08:00 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lemon_group.name
     *
     * @param name the value for lemon_group.name
     *
     * @mbggenerated Wed Jun 08 09:49:09 GMT+08:00 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}